<html>
 <head>
   <title>Kariéra NHL</title>
   <body style="background-color: aqua; color: black;">
 </head>
 <body>
   <h1>Sidney Crosby NHL Kariéra</h1>
   Do své druhé sezóny (06/07) vlétl jako uragán. Připsal si 120 bodů, suverénně ovládl kanadské bodování a získal Art Ross Trophy. Na udílení cen pak dostal ještě Hart Memorial Trophy pro nejužitečnějšího hráče a Ted Lindsay Award pro nejužitečnějšího hráče voleného samotnými hráči. V sezóně 07/08 nastoupil vinou zranění jen do 53 utkání, avšak připsal si v nich i tak skvělých 72 bodů. Poprvé se také dočkal výraznějšího úspěchu v playoff, kdy se dostal se svým týmem až finále, kde podlehl Detroitu. O rok později (08/09) přesáhl opět 100 bodů a v playoff se opět dostal až do finále a opět proti stejnému soupeři. Tam tentokrát uspěl a se svými Tučňáky porazil Detroit Red Wings 4:3 na zápasy. Stal se nejmladším kapitánem, který dovedl svůj tým až ke Stanley Cupu. V další sezóně (09/10) byl, jak už se stalo zvykem, opět nejlepší. Získal 109 bodů, nastřílel 51 gólů a získal Maurice Richard Trophy. Na udílení cen dostal Mark Messier Leadership Award udělovanou hráči s největšími vůdčími schopnostmi na ledě i mimo něj. Hned následující sezóna (10/11) byla speciální, byla výluka NHL a bylo odehráno jen 41 utkání. Sezónu 11/12 měl životně rozehranou, pak přišel šok. Sidney utrpěl otřes mozku a hrozil mu konec kariéry. Chyběl více než rok. O rok později (12/13) se ale očekával velký návrat. Král NHL byl zpět a hned dostal cenu Ted Lindsay Award. V sezóně 13/14 už byl v plné síle, vyhrál kanadské bodování a Art Ross Trophy, Hart Memorial Trophy a stejně jako minulý rok Ted Lindsay Award. Sezóna 14/15 byla snad jeho jediná, která byla klubově „neúspěsná“. Tým Pittsburgh Penguins prošel „přestavbou“. A vyplatilo se, hned další rok (15/16) vyhrál Stanley Cup a získal Conn Smythe Trophy pro nejužitečnějšiho hráče playoff. Sezóna 16/17 se zapíše do historie. Sidney a jeho Pittsburgh Penguins dokázali jako první obhájit v době platových stropů Stanley Cup a zároveň dokázal obhájit Conn Smythe Trophy, teprve jako 3. hráč v celé historii. Ještě v základní části byl nejlepším střelcem soutěže a dostal Maurice Richard Trophy.
 </body>
</html> 